services:
  api:
    build: .
    container_name: persona-engine
    restart: always
    ports:
      - "4000:3000"
    environment:
      - MONGO_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/personalization?replicaSet=rs0
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - personalization-net

  # MongoDB Replica Set Node 1
  mongo1:
    image: mongo:6
    container_name: mongo1
    command: mongod --replSet rs0 --port 27017
    ports:
      - "27100:27017"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongo1_data:/data/db
    networks:
      - personalization-net

  # MongoDB Replica Set Node 2
  mongo2:
    image: mongo:6
    container_name: mongo2
    command: mongod --replSet rs0 --port 27018
    ports:
      - "27101:27018"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --port 27018 --quiet --eval 'db.runCommand({ ping: 1 }).ok'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongo2_data:/data/db
    networks:
      - personalization-net

  # MongoDB Replica Set Node 3
  mongo3:
    image: mongo:6
    container_name: mongo3
    command: mongod --replSet rs0 --port 27019
    ports:
      - "27102:27019"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --port 27019 --quiet --eval 'db.runCommand({ ping: 1 }).ok'" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongo3_data:/data/db
    networks:
      - personalization-net

  # Replica Set Initializer
  mongo-setup:
    image: mongo:6
    container_name: mongo-setup
    depends_on:
      mongo1:
        condition: service_started
      mongo2:
        condition: service_started
      mongo3:
        condition: service_started
    entrypoint: [ "bash", "/docker-entrypoint-initdb.d/mongo-init.sh" ]
    volumes:
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - personalization-net

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-persona
    restart: always
    ports:
      - "6381:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - personalization-net

  # Postgres
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personalization-net

  #Event-worker
  event-worker:
    build: .
    container_name: event-worker
    restart: always
    command: [ "npm", "run", "start:worker" ]
    depends_on:
      - mongo-setup
      - redis
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - personalization-net
  #Batch-worker
  batch-worker:
    build: .
    container_name: batch-worker
    restart: always
    command: [ "node", "dist/worker/b-anal.worker.js" ]
    depends_on:
      postgres:
        condition: service_healthy
      mongo-setup:
        condition: service_completed_successfully
    environment:
      - MONGO_URL=${MONGO_URL}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - personalization-net

networks:
  personalization-net:


volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  postgres_data:
